// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/Prajithp/argosync/pkg/models"
)

func newApplication(db *gorm.DB, opts ...gen.DOOption) application {
	_application := application{}

	_application.applicationDo.UseDB(db, opts...)
	_application.applicationDo.UseModel(&models.Application{})

	tableName := _application.applicationDo.TableName()
	_application.ALL = field.NewAsterisk(tableName)
	_application.ID = field.NewUint(tableName, "id")
	_application.CreatedAt = field.NewTime(tableName, "created_at")
	_application.UpdatedAt = field.NewTime(tableName, "updated_at")
	_application.DeletedAt = field.NewField(tableName, "deleted_at")
	_application.Name = field.NewString(tableName, "name")
	_application.Deployments = applicationHasManyDeployments{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Deployments", "models.Deployment"),
		Application: struct {
			field.RelationField
			Deployments struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Deployments.Application", "models.Application"),
			Deployments: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Deployments.Application.Deployments", "models.Deployment"),
			},
		},
		Environment: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Deployments.Environment", "models.Environment"),
		},
		Region: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Deployments.Region", "models.Region"),
		},
		RollbackTarget: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Deployments.RollbackTarget", "models.Deployment"),
		},
	}

	_application.fillFieldMap()

	return _application
}

type application struct {
	applicationDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	DeletedAt   field.Field
	Name        field.String
	Deployments applicationHasManyDeployments

	fieldMap map[string]field.Expr
}

func (a application) Table(newTableName string) *application {
	a.applicationDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a application) As(alias string) *application {
	a.applicationDo.DO = *(a.applicationDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *application) updateTableName(table string) *application {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Name = field.NewString(table, "name")

	a.fillFieldMap()

	return a
}

func (a *application) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *application) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["name"] = a.Name

}

func (a application) clone(db *gorm.DB) application {
	a.applicationDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Deployments.db = db.Session(&gorm.Session{Initialized: true})
	a.Deployments.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a application) replaceDB(db *gorm.DB) application {
	a.applicationDo.ReplaceDB(db)
	a.Deployments.db = db.Session(&gorm.Session{})
	return a
}

type applicationHasManyDeployments struct {
	db *gorm.DB

	field.RelationField

	Application struct {
		field.RelationField
		Deployments struct {
			field.RelationField
		}
	}
	Environment struct {
		field.RelationField
	}
	Region struct {
		field.RelationField
	}
	RollbackTarget struct {
		field.RelationField
	}
}

func (a applicationHasManyDeployments) Where(conds ...field.Expr) *applicationHasManyDeployments {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a applicationHasManyDeployments) WithContext(ctx context.Context) *applicationHasManyDeployments {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a applicationHasManyDeployments) Session(session *gorm.Session) *applicationHasManyDeployments {
	a.db = a.db.Session(session)
	return &a
}

func (a applicationHasManyDeployments) Model(m *models.Application) *applicationHasManyDeploymentsTx {
	return &applicationHasManyDeploymentsTx{a.db.Model(m).Association(a.Name())}
}

func (a applicationHasManyDeployments) Unscoped() *applicationHasManyDeployments {
	a.db = a.db.Unscoped()
	return &a
}

type applicationHasManyDeploymentsTx struct{ tx *gorm.Association }

func (a applicationHasManyDeploymentsTx) Find() (result []*models.Deployment, err error) {
	return result, a.tx.Find(&result)
}

func (a applicationHasManyDeploymentsTx) Append(values ...*models.Deployment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a applicationHasManyDeploymentsTx) Replace(values ...*models.Deployment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a applicationHasManyDeploymentsTx) Delete(values ...*models.Deployment) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a applicationHasManyDeploymentsTx) Clear() error {
	return a.tx.Clear()
}

func (a applicationHasManyDeploymentsTx) Count() int64 {
	return a.tx.Count()
}

func (a applicationHasManyDeploymentsTx) Unscoped() *applicationHasManyDeploymentsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type applicationDo struct{ gen.DO }

type IApplicationDo interface {
	gen.SubQuery
	Debug() IApplicationDo
	WithContext(ctx context.Context) IApplicationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IApplicationDo
	WriteDB() IApplicationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IApplicationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IApplicationDo
	Not(conds ...gen.Condition) IApplicationDo
	Or(conds ...gen.Condition) IApplicationDo
	Select(conds ...field.Expr) IApplicationDo
	Where(conds ...gen.Condition) IApplicationDo
	Order(conds ...field.Expr) IApplicationDo
	Distinct(cols ...field.Expr) IApplicationDo
	Omit(cols ...field.Expr) IApplicationDo
	Join(table schema.Tabler, on ...field.Expr) IApplicationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IApplicationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IApplicationDo
	Group(cols ...field.Expr) IApplicationDo
	Having(conds ...gen.Condition) IApplicationDo
	Limit(limit int) IApplicationDo
	Offset(offset int) IApplicationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IApplicationDo
	Unscoped() IApplicationDo
	Create(values ...*models.Application) error
	CreateInBatches(values []*models.Application, batchSize int) error
	Save(values ...*models.Application) error
	First() (*models.Application, error)
	Take() (*models.Application, error)
	Last() (*models.Application, error)
	Find() ([]*models.Application, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Application, err error)
	FindInBatches(result *[]*models.Application, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Application) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IApplicationDo
	Assign(attrs ...field.AssignExpr) IApplicationDo
	Joins(fields ...field.RelationField) IApplicationDo
	Preload(fields ...field.RelationField) IApplicationDo
	FirstOrInit() (*models.Application, error)
	FirstOrCreate() (*models.Application, error)
	FindByPage(offset int, limit int) (result []*models.Application, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IApplicationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a applicationDo) Debug() IApplicationDo {
	return a.withDO(a.DO.Debug())
}

func (a applicationDo) WithContext(ctx context.Context) IApplicationDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a applicationDo) ReadDB() IApplicationDo {
	return a.Clauses(dbresolver.Read)
}

func (a applicationDo) WriteDB() IApplicationDo {
	return a.Clauses(dbresolver.Write)
}

func (a applicationDo) Session(config *gorm.Session) IApplicationDo {
	return a.withDO(a.DO.Session(config))
}

func (a applicationDo) Clauses(conds ...clause.Expression) IApplicationDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a applicationDo) Returning(value interface{}, columns ...string) IApplicationDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a applicationDo) Not(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a applicationDo) Or(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a applicationDo) Select(conds ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a applicationDo) Where(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a applicationDo) Order(conds ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a applicationDo) Distinct(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a applicationDo) Omit(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a applicationDo) Join(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a applicationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a applicationDo) RightJoin(table schema.Tabler, on ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a applicationDo) Group(cols ...field.Expr) IApplicationDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a applicationDo) Having(conds ...gen.Condition) IApplicationDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a applicationDo) Limit(limit int) IApplicationDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a applicationDo) Offset(offset int) IApplicationDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a applicationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IApplicationDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a applicationDo) Unscoped() IApplicationDo {
	return a.withDO(a.DO.Unscoped())
}

func (a applicationDo) Create(values ...*models.Application) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a applicationDo) CreateInBatches(values []*models.Application, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a applicationDo) Save(values ...*models.Application) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a applicationDo) First() (*models.Application, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Application), nil
	}
}

func (a applicationDo) Take() (*models.Application, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Application), nil
	}
}

func (a applicationDo) Last() (*models.Application, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Application), nil
	}
}

func (a applicationDo) Find() ([]*models.Application, error) {
	result, err := a.DO.Find()
	return result.([]*models.Application), err
}

func (a applicationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Application, err error) {
	buf := make([]*models.Application, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a applicationDo) FindInBatches(result *[]*models.Application, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a applicationDo) Attrs(attrs ...field.AssignExpr) IApplicationDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a applicationDo) Assign(attrs ...field.AssignExpr) IApplicationDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a applicationDo) Joins(fields ...field.RelationField) IApplicationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a applicationDo) Preload(fields ...field.RelationField) IApplicationDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a applicationDo) FirstOrInit() (*models.Application, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Application), nil
	}
}

func (a applicationDo) FirstOrCreate() (*models.Application, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Application), nil
	}
}

func (a applicationDo) FindByPage(offset int, limit int) (result []*models.Application, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a applicationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a applicationDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a applicationDo) Delete(models ...*models.Application) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *applicationDo) withDO(do gen.Dao) *applicationDo {
	a.DO = *do.(*gen.DO)
	return a
}
